title: Max's Favorite Things
theme: minima
author: Max Abramsky
email: windowfish28@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog containing all of my favorite things!

# social links
twitter_username: MaximumGrimm # DO NOT include the @ character, or else the build will fail!
github_username:  MaxAbramsky # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
